USE ECOMMERCE;

SELECT * FROM CATEGORY;
SELECT * FROM PRODUCT;
SELECT * FROM SELLER;
SELECT * FROM INVENTORY;
SELECT * FROM ORDERTABLE;
SELECT * FROM ORDERDETAIL;
SELECT * FROM REVIEWING;
SELECT * FROM RATE;


SELECT DISTINCT CATEGORYID
FROM PRODUCT;

SELECT DISTINCT ORDER_STATUS
FROM ORDERTABLE;

SELECT DISTINCT REVIEW_TEXT
FROM REVIEWING;

SELECT DISTINCT RATING
FROM RATE;

SELECT * FROM INVENTORY
WHERE STOCK < 20;

SELECT * FROM INVENTORY
WHERE STOCK > 20;

SELECT * FROM INVENTORY
WHERE STOCK = 0;

SELECT * FROM INVENTORY
WHERE STATUS = 'AVAILABLE';

SELECT * FROM ORDERTABLE
WHERE CUSTOMER_NAME = 'Anitha';

SELECT * FROM ORDERTABLE
WHERE ORDER_STATUS = 'Pending';

SELECT * FROM ORDERTABLE
WHERE ORDER_STATUS = 'Shipped';

SELECT * FROM ORDERTABLE
WHERE ORDER_STATUS = 'Delivered';

SELECT * FROM REVIEWING
WHERE REVIEW_TEXT = 'GOOD';

SELECT * FROM REVIEWING
WHERE REVIEW_TEXT = 'EXCELLENT';

SELECT * FROM REVIEWING
WHERE REVIEW_TEXT = 'BAD QUALITY';

SELECT * FROM RATE
WHERE RATING = 5;

SELECT * FROM RATE
WHERE RATING >= 4;



SELECT * FROM PRODUCT
ORDER BY CATEGORYID;

SELECT * FROM INVENTORY
ORDER BY STOCK DESC;

SELECT * FROM ORDERTABLE
ORDER BY CUSTOMER_NAME, ORDER_DATE;

SELECT * FROM REVIEWING
ORDER BY CUSTOMER_NAME ASC;

SELECT * FROM REVIEWING
ORDER BY REVIEW_DATE DESC;

SELECT * FROM REVIEWING
ORDER BY PRODUCTID ASC;

SELECT * FROM RATE
ORDER BY RATING DESC;

SELECT * FROM RATE
ORDER BY RATING ASC;